# Generated by Django 4.2.7 on 2023-11-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuLink',
        ),
    ]
